CREATE TABLE public.characters
(
    guid         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (guid BETWEEN 1 AND 4294967295),
    account_id   BIGINT      NOT NULL REFERENCES public.account (id),
    name         TEXT        NOT NULL UNIQUE CHECK (LENGTH(name) BETWEEN 2 AND 12),
    race         SMALLINT    NOT NULL CHECK (race = ANY (ARRAY [1, 2, 3, 4, 5, 6, 7, 8, 10, 11])),
    class        SMALLINT    NOT NULL CHECK (class = ANY (ARRAY [1, 2, 3, 4, 5, 6, 7, 8, 9, 11])),
    gender       SMALLINT    NOT NULL CHECK (gender = ANY (ARRAY [0, 1])),
    skin         SMALLINT    NOT NULL CHECK (skin BETWEEN 0 AND 255),
    face         SMALLINT    NOT NULL CHECK (face BETWEEN 0 AND 255),
    hair_style   SMALLINT    NOT NULL CHECK (hair_style BETWEEN 0 AND 255),
    hair_color   SMALLINT    NOT NULL CHECK (hair_color BETWEEN 0 AND 255),
    facial_style SMALLINT    NOT NULL CHECK (facial_style BETWEEN 0 AND 255),
    level        SMALLINT    NOT NULL CHECK (level BETWEEN 1 AND 80),
    map_id       INTEGER     NOT NULL CHECK (map_id BETWEEN 0 AND 65535),
    zone_id      INTEGER     NOT NULL CHECK (zone_id BETWEEN 0 AND 65535),
    position_x   REAL        NOT NULL,
    position_y   REAL        NOT NULL,
    position_z   REAL        NOT NULL,
    orientation  REAL        NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP

);

CREATE INDEX characters_account_id_idx
    ON public.characters USING BTREE (account_id);

ALTER TABLE public.characters
    ENABLE ROW LEVEL SECURITY;

REVOKE ALL PRIVILEGES ON TABLE public.characters
    FROM anon, authenticated, service_role;