CREATE TABLE public.characters (
    guid         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account_id   BIGINT                                  NOT NULL,
    name         TEXT                                    NOT NULL,
    race         SMALLINT                                NOT NULL,
    class        SMALLINT                                NOT NULL,
    gender       SMALLINT                                NOT NULL,
    skin         SMALLINT                                NOT NULL,
    face         SMALLINT                                NOT NULL,
    hair_style   SMALLINT                                NOT NULL,
    hair_color   SMALLINT                                NOT NULL,
    facial_style SMALLINT                                NOT NULL,
    level        SMALLINT                                NOT NULL,
    map_id       INTEGER                                 NOT NULL,
    zone_id      INTEGER                                 NOT NULL,
    position_x   REAL                                    NOT NULL,
    position_y   REAL                                    NOT NULL,
    position_z   REAL                                    NOT NULL,
    orientation  REAL                                    NOT NULL,
    created_at   TIMESTAMPTZ                             NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE public.characters ENABLE ROW LEVEL SECURITY;

CREATE INDEX characters_account_id_idx
    ON public.characters USING BTREE (account_id);

CREATE UNIQUE INDEX characters_name_key
    ON public.characters USING BTREE (name);

CREATE UNIQUE INDEX characters_pkey
    ON public.characters USING BTREE (guid);

ALTER TABLE public.characters
    ADD CONSTRAINT characters_pkey
        PRIMARY KEY USING INDEX characters_pkey;

ALTER TABLE public.characters
    ADD CONSTRAINT characters_account_id_fkey
        FOREIGN KEY (account_id) REFERENCES public.account (id) NOT VALID;

ALTER TABLE public.characters
    VALIDATE CONSTRAINT characters_account_id_fkey;

ALTER TABLE public.characters
    ADD CONSTRAINT characters_class_check
        CHECK (class = ANY (ARRAY[1, 2, 3, 4, 5, 6, 7, 8, 9, 11])) NOT VALID;

ALTER TABLE public.characters
    VALIDATE CONSTRAINT characters_class_check;

ALTER TABLE public.characters
    ADD CONSTRAINT characters_face_check
        CHECK (face BETWEEN 0 AND 255) NOT VALID;

ALTER TABLE public.characters
    VALIDATE CONSTRAINT characters_face_check;

ALTER TABLE public.characters
    ADD CONSTRAINT characters_facial_style_check
        CHECK (facial_style BETWEEN 0 AND 255) NOT VALID;

ALTER TABLE public.characters
    VALIDATE CONSTRAINT characters_facial_style_check;

ALTER TABLE public.characters
    ADD CONSTRAINT characters_gender_check
        CHECK (gender = ANY (ARRAY[0, 1])) NOT VALID;

ALTER TABLE public.characters
    VALIDATE CONSTRAINT characters_gender_check;

ALTER TABLE public.characters
    ADD CONSTRAINT characters_guid_check
        CHECK (guid BETWEEN 1 AND 4294967295) NOT VALID;

ALTER TABLE public.characters
    VALIDATE CONSTRAINT characters_guid_check;

ALTER TABLE public.characters
    ADD CONSTRAINT characters_hair_color_check
        CHECK (hair_color BETWEEN 0 AND 255) NOT VALID;

ALTER TABLE public.characters
    VALIDATE CONSTRAINT characters_hair_color_check;

ALTER TABLE public.characters
    ADD CONSTRAINT characters_hair_style_check
        CHECK (hair_style BETWEEN 0 AND 255) NOT VALID;

ALTER TABLE public.characters
    VALIDATE CONSTRAINT characters_hair_style_check;

ALTER TABLE public.characters
    ADD CONSTRAINT characters_level_check
        CHECK (level BETWEEN 1 AND 80) NOT VALID;

ALTER TABLE public.characters
    VALIDATE CONSTRAINT characters_level_check;

ALTER TABLE public.characters
    ADD CONSTRAINT characters_map_id_check
        CHECK (map_id BETWEEN 0 AND 65535) NOT VALID;

ALTER TABLE public.characters
    VALIDATE CONSTRAINT characters_map_id_check;

ALTER TABLE public.characters
    ADD CONSTRAINT characters_name_check
        CHECK (LENGTH(name) BETWEEN 2 AND 12) NOT VALID;

ALTER TABLE public.characters
    VALIDATE CONSTRAINT characters_name_check;

ALTER TABLE public.characters
    ADD CONSTRAINT characters_name_key
        UNIQUE USING INDEX characters_name_key;

ALTER TABLE public.characters
    ADD CONSTRAINT characters_race_check
        CHECK (race = ANY (ARRAY[1, 2, 3, 4, 5, 6, 7, 8, 10, 11])) NOT VALID;

ALTER TABLE public.characters
    VALIDATE CONSTRAINT characters_race_check;

ALTER TABLE public.characters
    ADD CONSTRAINT characters_skin_check
        CHECK (skin BETWEEN 0 AND 255) NOT VALID;

ALTER TABLE public.characters
    VALIDATE CONSTRAINT characters_skin_check;

ALTER TABLE public.characters
    ADD CONSTRAINT characters_zone_id_check
        CHECK (zone_id BETWEEN 0 AND 65535) NOT VALID;

ALTER TABLE public.characters
    VALIDATE CONSTRAINT characters_zone_id_check;

REVOKE ALL PRIVILEGES ON TABLE public.characters
FROM anon, authenticated, service_role;
